---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%",
  message = FALSE,
  warning = FALSE
)
```

# cts

<!-- badges: start -->
<!-- badges: end -->

The goal of cts is to ...

## Installation

You can install the development version of cts from [GitHub](https://github.com/) with:

``` r
# install.packages("pak")
pak::pak("esqLABS/cts")
```

## Example

### List available compounds building blocks

```{r example, attr.output='style="max-height: 100px;"'}
library(cts)

# List available compounds building blocks
list_compounds()
```
### Import compound snapshot

#### From OSP qualified building blocks
```{r}
rifampicin <- compound("Rifampicin")

midazolam <- compound("Midazolam")
```

#### From URL

```{r, eval = FALSE}
compound("https://raw.githubusercontent.com/Open-Systems-Pharmacology/Alfentanil-Model/v2.2/Alfentanil-Model.json")
```


#### From File

```{r, eval = FALSE}
compound("path/to/Alfentanil-Model.json")
```


### Explore Compound

```{r}
rifampicin$Formulations
```


